[build]
publish = "public"
command = "git submodule update --remote data/comments && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "v0.68.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
