[build]
publish = "public"
command = "git submodule update --remote data/comments && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "v0.68.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true